{% set version = "1.4.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpostgres
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RPostgres_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RPostgres/RPostgres_{{ version }}.tar.gz
  sha256: c9cc0648c432f837fd0eb4922db4903357244d5a2cedd04ea236f249b08acdfc

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-hms                      # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-bit64                    # [build_platform != target_platform]
    - r-plogr                    # [build_platform != target_platform]
    - r-withr                    # [build_platform != target_platform]
    - r-bh                       # [build_platform != target_platform]
    - r-blob                     # [build_platform != target_platform]
    - r-dbi                      # [build_platform != target_platform]
    - r-lubridate                # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-dbi >=1.1.0
    - r-rcpp >=0.11.4.2
    - r-bit64
    - r-blob >=1.2.0
    - r-hms >=0.5.0
    - r-lubridate
    - r-plogr >=0.2.0
    - r-withr
    - postgresql
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    # BH is the header-only part of Boost and thus a compile-time requirement only
    # - r-bh
    - r-dbi >=1.1.0
    - r-rcpp >=0.11.4.2
    - r-bit64
    - r-blob >=1.2.0
    - r-hms >=0.5.0
    - r-lubridate
    - r-plogr >=0.2.0
    - r-withr
    - libpq

test:
  commands:
    - $R -e "library('RPostgres')"           # [not win]
    - "\"%R%\" -e \"library('RPostgres')\""  # [win]
  requires:
    - conda-build

about:
  home: https://github.com/r-dbi/RPostgres
  license: GPL-3.0-only
  summary: |
    Fully 'DBI'-compliant 'Rcpp'-backed interface to 'PostgreSQL' <https://www.postgresql.org/>,
    an open-source relational database.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
    - fhoehle
