{% set version = "1.4.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rpostgres
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RPostgres_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RPostgres/RPostgres_{{ version }}.tar.gz
  sha256: 3dd1f1d83bd8a25a0a86532c6971072fccea7b1769f601ad9daa8c9aa8f66924

build:
  number: 2
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-dbi                      # [build_platform != target_platform]
    - r-bit64                    # [build_platform != target_platform]
    - r-blob                     # [build_platform != target_platform]
    - r-cpp11                    # [build_platform != target_platform]
    - r-hms                      # [build_platform != target_platform]
    - r-lubridate                # [build_platform != target_platform]
    - r-plogr                    # [build_platform != target_platform]
    - r-withr                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dbi >=1.2.0
    - r-bit64
    - r-blob >=1.2.0
    - r-cpp11
    - r-hms >=1.0.0
    - r-lubridate
    - r-plogr >=0.2.0
    - r-withr
    - postgresql
  run:
    - r-base
    - r-dbi >=1.2.0
    - r-bit64
    - r-blob >=1.2.0
    - r-cpp11
    - r-hms >=1.0.0
    - r-lubridate
    - r-plogr >=0.2.0
    - r-withr
    - libpq

test:
  commands:
    - $R -e "library('RPostgres')"           # [not win]
    - "\"%R%\" -e \"library('RPostgres')\""  # [win]
  requires:
    - conda-build

about:
  home: https://github.com/r-dbi/RPostgres
  license: MIT
  summary: |
    Fully 'DBI'-compliant 'Rcpp'-backed interface to 'PostgreSQL' <https://www.postgresql.org/>,
    an open-source relational database.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
    - fhoehle
