appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: qCVn6iuD+75GQlKQeAXgJKV/pc/F0SdFfza66nAVSxS1ZAlWV5BQAOz1P8Die9VxjE417ISmEssS56TDGO1wEy6Q2xkgXvE2/FXri0fKCgTj/VHrQ6+kaSHa1kDpssQ3Ber7DNFoqeb+Fa14R2vusIGDG3XiOocA/Ywbauf3ByEuM+Y8BGz6EPXvL3OuJ5SK+k+pEpIzhORKJS5GqZODfAgd8FeMdj2MGTbExXvuIBqIy7Pi2C3+Mj+nUvtzxGHsypKADo1hrP2e8Cl75GwGfgPLK72kgmLUsvprCF/pKM50PfCpUBW2pBuDII4KkpS4fzUl0sPYhBuMror6WIpe2Fqr0rC3K/SHLkoynvXa2P9Qm8F2dzZS2TBQbUgzwBr9gUGSCzf6Vml930uaN29/qcG2jl9sIAJixRB/RydjMcD91CUmRofMe7HQpmZ/letYQp77fdxy51wcl8y5b9xwbzhyn5o3OnQKHkYTERqocXOSLhltqg9qLQwXBFIeBKYKXzNRay3/kxljNwGZd+KdL79VFg6LP6iUArFbYDnkbRWgaLaltlyPJ+pLetYh9f8qPDUs6xTDc5Z5ftYENSaK1FbMKrD0cmEVtUAGjzAT1Tw3ueSPDHru3O3ZVAHUle0NsCUj9uCrstx0mhil+Vu//7tFheCc0A3CNR0zubwaD/I=
conda_forge_output_validation: false
